#!/bin/sh
#
# sshd        Starts sshd.
#

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

umask 077

start() {
	# Create any missing keys
    mkdir -p /home/admin/ssh
    chmod 0600 /home/admin/ssh
    if [ ! -f /home/admin/ssh/ssh_host_rsa_key ]; then
        ssh-keygen -q -N "" -t rsa -b 2048 -f /home/admin/ssh/ssh_host_rsa_key
    fi
    if [ ! -f /home/admin/ssh/ssh_host_ecdsa_key ]; then
        ssh-keygen -q -N "" -t ecdsa -f /home/admin/ssh/ssh_host_ecdsa_key
    fi
    if [ ! -f /home/admin/ssh/ssh_host_ed25519_key ]; then
        ssh-keygen -q -N "" -t ed25519 -f /home/admin/ssh/ssh_host_ed25519_key
    fi

	printf "Starting sshd: "
	/usr/sbin/sshd
	touch /var/lock/sshd
	echo "OK"
}
stop() {
	printf "Stopping sshd: "
	killall sshd
	rm -f /var/lock/sshd
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

